export const listThemeCard = [
	{
		title: "Ganyu",
		img: "/images/theme/card-list/card_theme_ganyu.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_ganyu.jpg",
			colorPrimary: "#1A3570",
			textHover: "#4C7CFF",
			layoutBg: "tranparent",
			layoutHeaderBg: "rgba(179, 216, 219, 0.8)",
			playerBg: "#A3D5DC",
			primaryBg: "#D1EDF0",
			textPrimary: "#32323d",
			textSecondary: "#333333b0",
			purplePrimary: "#1966B2",
			newSongLayout: "tranparent",
			borderPlayer: "rgba(0,0,0,0.15)",
			backgrondSize: "cover",
			sidebarPoup: "#cce0e0",
		},
	},
	{
		title: "Mặc định",
		img: "/images/theme/card-list/card_theme_purple.jpg",
		properties: {
			colorPrimary: "#170f23",
			textHover: "#c273ed",
			layoutBg: "#170f23",
			sidebarBg: "#231b2e",
			layoutHeaderBg: "rgba(23, 15, 35, 0.666)",
			playerBg: "#130c1c",
			primaryBg: "#34224f",
			textPrimary: "#fff",
			textSecondary: "hsla(0, 0%, 100%, 0.5)",
			purplePrimary: "#9b4de0",
			newSongLayout: "url(https://zjs.zmdcdn.me/zmp3-desktop/releases/v1.9.9/static/media/new-release-bg.73d8f976.jpg)",
			borderPlayer: "hsla(0,0%,100%,0.1)",
			sidebarPoup: "#2a213a",
		},
	},
	{
		title: "Jack",
		img: "/images/theme/card-list/card_theme_jack.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_jack.jpg",
			colorPrimary: "#D08011",
			textHover: "#F59D22",
			playerBg: "#4C473E",
			layoutHeaderBg: "#767269cc",
			layoutBg: "tranparentent",
			primaryBg: "#605C52",
			textPrimary: "#FFFF",
			textSecondary: "hsla(0,0%,100%,0.5)",
			purplePrimary: "#D08011",
			newSongLayout: "tranparent",
			borderPlayer: "rgba(0,0,0,0.05)",
			sidebarPoup: "#604a45",
		},
	},
	{
		title: "Jennie",
		img: "/images/theme/card-list/card_theme_jennie.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_jennie.jpg",
			colorPrimary: "#BBB9C4",
			textHover: "#6F1F89",
			layoutBg: "tranparent",
			layoutHeaderBg: "#bbb9c4cc",
			playerBg: "#C6C4D1",
			primaryBg: "#CAC6DD",
			textPrimary: "#32323d",
			textSecondary: "#696969",
			purplePrimary: "#8919AE",
			newSongLayout: "tranparent",
			borderPlayer: "rgba(0,0,0,0.1)",
			sidebarPoup: "#f2f2f2",
		},
	},
	{
		title: "Jisoo",
		img: "/images/theme/card-list/card_theme_jiiso.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_jisoo.jpg",
			colorPrimary: "#8D22C3",
			textHover: "#8D22C3",
			layoutBg: "tranparent",
			layoutHeaderBg: "rgb(241, 221, 216, 0.8)",
			playerBg: "#F5E6E0",
			primaryBg: "#FFFF",
			textPrimary: "#32323d",
			textSecondary: "rgba(0,0,0,0.6)",
			purplePrimary: "#8D22C3",
			newSongLayout: "tranparent",
			borderPlayer: "rgba(0,0,0,0.15)",
			sidebarPoup: "#f2f2f2",
		},
	},
	{
		title: "Rose",
		img: "/images/theme/card-list/card_theme_rose.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_rose.jpg",
			colorPrimary: "#1A3570",
			textHover: "#4C7CFF",
			layoutBg: "tranparent",
			layoutHeaderBg: "#061c4fcc",
			playerBg: "#061641",
			primaryBg: "#1A3570",
			textPrimary: "#fff",
			textSecondary: "hsla(0,0%,100%,0.5)",
			purplePrimary: "#3560F5",
			newSongLayout: "tranparent",
			borderPlayer: "hsla(0,0%,100%,0.1)",
			sidebarPoup: "#1d2a49",
		},
	},
	{
		title: "IU",
		img: "/images/theme/card-list/card_theme_iu.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_ui.jpg",
			colorPrimary: "#EFEDEB",
			textHover: "#AC3E82",
			layoutBg: "tranparent",
			layoutHeaderBg: "rgb(241, 221, 216, 0.8)",
			playerBg: "#F5E6E0",
			primaryBg: "#EFEDEB",
			textPrimary: "#000",
			textSecondary: "#696969",
			purplePrimary: "#C24793",
			newSongLayout: "tranparent",
			borderPlayer: "rgba(0,0,0,0.1)",
			sidebarPoup: "#f2f2f2",
		},
	},
	{
		title: "Lisa",
		img: "/images/theme/card-list/card_theme_lisa.jpg",
		properties: {
			backgroundImg: "/images/theme/img-background_lisa.jpg",
			colorPrimary: "##D14781",
			textHover: "#CC3373",
			layoutBg: "tranparent",
			layoutHeaderBg: "rgb(241, 221, 216, 0.8)",
			playerBg: "#F4CBCA",
			primaryBg: "#F9E6E2",
			textPrimary: "#32323d",
			textSecondary: "#696969",
			purplePrimary: "#D14781",
			newSongLayout: "tranparent",
			borderPlayer: "rgba(0,0,0,0.1)",
			sidebarPoup: "#fbd3d2",
		},
	},
	,
];
